walmart_project:
  outputs:
    dev:
      catalog: catalog name
      host: host path
      http_path: your access path
      schema: your schema
      threads: 1
      token: your token
      type: databricks
  target: dev
