walmart_project:
  outputs:
    dev:
      catalog: walmart_project
      host: dbc-345da47f-f997.cloud.databricks.com
      http_path: /sql/1.0/warehouses/2f682223358cb75a
      schema: bronze_data
      threads: 1
      token: dapi99fc367e6d6509789ca7b72e38890495
      type: databricks
  target: dev
