sources:
  - name: walmart_databricks
    database: walmart_project
    schema: bronze_data
    tables:
      - name: customers
      - name: employees
      - name: order_items
      - name: orders
      - name: products
      - name: stores